# Generated by Django 2.2.4 on 2019-09-30 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='order',
        ),
        migrations.AddField(
            model_name='page',
            name='address',
            field=models.CharField(default=1, max_length=200, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.custom_upload_to),
        ),
        migrations.AddField(
            model_name='page',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='created_by',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
