# Generated by Django 2.2.4 on 2019-10-11 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190930_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='address',
        ),
        migrations.RemoveField(
            model_name='page',
            name='price',
        ),
    ]
